apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: azure-bar
  janus-idp.io/tekton: azure-bar
  backstage.io/kubernetes-id: azure-bar
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: azure-bar
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
